name: Update README with GitHub Stats

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 * * * *'  # Actualización cada hora

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Update README with stats
              env:
                  PATH_KEY: ${{ secrets.PATH_KEY }}
              run: |
                  echo "<h1 align='center'>HI!!</h1>" > README.md
                  echo "" >> README.md
                  echo "- ➡️ Contact **gonzalojimenezcarretero@gmail.com**" >> README.md
                  echo "- I am currently a student." >> README.md
                  echo "## 🛠️ Programming languages I have experience with" >> README.md
                  echo "<br />" >> README.md
                  echo "<div style='display: flex; align-items: center; gap: 10px;'>" >> README.md
                  echo "<a href='https://www.python.org' target='_blank'><img height='40' src='https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg' alt='Python'/></a>" >> README.md
                  echo "<a href='https://en.wikipedia.org/wiki/C_(programming_language)' target='_blank'><img height='40' src='https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg' alt='C'/></a>" >> README.md
                  echo "<a href='https://www.java.com' target='_blank'><img height='40' src='https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg' alt='Java'/></a>" >> README.md
                  echo "</div>" >> README.md
                  echo "" >> README.md
                  echo "## 🔥 Streak Stats" >> README.md
                  echo "<p align='center'><img src='https://github-readme-streak-stats.herokuapp.com/?user=GonzaloJCC&theme=algolia' alt='GonzaloJCC' /></p>" >> README.md
                  echo "" >> README.md
                  echo "### ⚙️ &nbsp;GitHub Analytics" >> README.md
                  echo "<p align='center'>" >> README.md
                  echo "<a href='https://github.com/GonzaloJCC'>" >> README.md
                  echo "<img height='180em' src='https://github-readme-stats-eight-theta.vercel.app/api?username=GonzaloJCC&show_icons=true&theme=algolia&include_all_commits=true&count_private=true&token=${KEY}'/>" >> README.md
                  echo "<img height='180em' src='https://github-readme-stats-eight-theta.vercel.app/api/top-langs/?username=GonzaloJCC&layout=compact&langs_count=8&theme=algolia&count_private=true&token=${KEY}'/>" >> README.md
                  echo "</a>" >> README.md
                  echo "</p>" >> README.md
                  echo "" >> README.md
                  echo "<img align='right' width='1050' alt='snake2' src='https://imgur.com/uqIdteX.png' />" >> README.md

            - name: Commit changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add README.md
                  git commit -m "Update README with GitHub Stats"
                  git push
